//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YazilimYapimi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kelime
    {
        public int ID { get; set; }
        public string Word { get; set; }
        public string Type { get; set; }
        public string TurkceKarsiligi { get; set; }
        public string OrnekCumle { get; set; }
        public int BilmeSayisi { get; set; }
        public Nullable<System.DateTime> BilinmeTarihi { get; set; }
    }
}
