//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YazilimYapimi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarih
    {
        public int ayID { get; set; }
        public Nullable<int> Ocak { get; set; }
        public Nullable<int> Subat { get; set; }
        public Nullable<int> Mart { get; set; }
        public Nullable<int> Nisan { get; set; }
        public Nullable<int> Mayis { get; set; }
        public Nullable<int> Haziran { get; set; }
        public Nullable<int> Temmuz { get; set; }
        public Nullable<int> Agustos { get; set; }
        public Nullable<int> Eylül { get; set; }
        public Nullable<int> Ekim { get; set; }
        public Nullable<int> Kasim { get; set; }
        public Nullable<int> Aralik { get; set; }
    }
}
